### PR TITLE
Moving to SDL and Vulkan

### PR DESCRIPTION
**Pull request by sepcnt**
- Fix error in MSVC
- Use _MSC_VER macro

### CODE REVIEW

**Comment by minerscale** [comment]
Hi!

Porting away from bass is really hard, actually. The game uses specially modified extended module tracker files in a special file format that I'm pretty sure can only be handled by bass. So in order to port it you would have to write a reader for that specific format and then use some other xm player (or if you're feeling very adventurous implement it yourself).

The caching isn't done by bass either so you can actually just turn it off and it's fine. (it's in DSoundManager.cpp).

That said I would love some help on the matter since transitioning away from bass would make the software significantly more cross platform (since bass is not open source). I'm just not sure if you know what you're getting into!

Edit:

Why are you deprecating zlib in replacement for SDL? Seems like an extra dependency for no reason since SDL will be using zlib and libpng under the hood anyway. libpng depends on the zlib that is built too so you're not even replacing one dependency with another. If you have any insight that would be greatly appreciated.

Edit edit:

I think the future of the project also lies in my current feature branch sexy-vk, which I successfully removed all windows specific code and got a Linux build running! I would love help getting it running on windows and the latest commits of that are available on my fork: https://github.com/minerscale/re-plants-vs-zombies

**Comment by sepcnt** [comment]
Deprecating ZLib was a mistake, but the libpng and libjpeg used by imagelib could be removed. SDL_image handles all kinds of image RW well. As for the xm, SDL_sound may work with some modification or I would try to use https://github.com/Artefact2/libxm

**Comment by minerscale** [comment]
You make a good argument for SDL. The game doesn't actually use any shaders. My sexy-vk branch uses them but the base game is all fixed-function amazingly. (also it mostly software renders even with hardware acceleration turned on.) I've done a ton of work porting the graphics API to vulkan and it's working very nicely now. Check out my latest sexy-vk branch on minerscale/re-plants-vs-zombies for my commits.

**Comment by minerscale** [comment]
Also, do contact me on discord @minerscale  so we can discuss what it even means to merge these changes if possible.

**Pull request closed without merging**
